server.address=0.0.0.0
server.port=8080
spring.application.name=anniversary-backend

# Unlock Date: April 7, 2025, 12:00 AM
app.unlock.date=2025-04-07T00:00:00
app.unlock.timezone=Asia/Kolkata

# Password (you can change this!)
app.unlock.password=Pagelidhana1615